[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
name = "zstd"
version = "0.1.0"
build = "src/build.rs"
description = "Rust zstd bindings library."
documentation = "https://gyscos.github.io/zstd-rs/zstd/index.html"
repository = "https://github.com/Gyscos/zstd-rs"
license = "MIT"

[[bin]]
name = "zstd"
test = false
doc = false

[dependencies]
libc = "0.2.5"

[build-dependencies]
gcc = "0.3.21"
