[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
name = "zstd"
version = "0.1.0"
build = "src/build.rs"
description = "Rust zstd bindings library."
license = "MIT"

[dependencies]
libc = "0.2.5"

[build-dependencies]
gcc = "0.3.21"
