[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
build = "src/build.rs"
description = "Rust zstd bindings library."
documentation = "https://gyscos.github.io/zstd-rs/zstd/index.html"
license = "MIT"
name = "zstd"
repository = "https://github.com/Gyscos/zstd-rs"
version = "0.1.1"

[[bin]]
doc = false
name = "zstd"
test = false

[[bin]]
doc = false
name = "stream"
test = false

[[bin]]
doc = false
name = "train"
test = false

[build-dependencies]
gcc = "0.3.21"

[dependencies]
libc = "0.2.5"
